#!/system/bin/sh

zram_enabled=1
DISK_SIZE=150

if($zram_enabled == 1); then

    swappiness=70
    echo $swapiness > /proc/sys/vm/swappiness
    echo 1 > /sys/block/zram0/reset
    echo $(($DISK_SIZE*1024*1024)) > /sys/block/zram0/disksize
    mknod /dev/zram0 b 253 0
    mkswap /dev/zram0
    swapon /dev/zram0
else
    swappiness=45
    echo $swappiness > /proc/sys/vm/swappiness

exit 0
